from google.cloud import bigquery

PAGE_SCHEMA = [
    bigquery.SchemaField("id","INTEGER",'NULLABLE'),
    bigquery.SchemaField("category","STRING"),
    bigquery.SchemaField("imageURI","STRING"),
    bigquery.SchemaField("likes","FLOAT"),
    bigquery.SchemaField("verification","STRING"),
    bigquery.SchemaField("name","STRING"),
    bigquery.SchemaField("country","STRING"),
    bigquery.SchemaField("entityType","STRING"),
    bigquery.SchemaField("igUsername","STRING"),
    bigquery.SchemaField("igFollowers","FLOAT"),
    bigquery.SchemaField("igVerification","STRING"),
    bigquery.SchemaField("pageAlias","STRING"),
    bigquery.SchemaField("pageIsDeleted","BOOLEAN"),
    bigquery.SchemaField("ScrapedDate","DATE")
]

AD_SCHEMA = [
    bigquery.SchemaField("adid","INTEGER"),
    bigquery.SchemaField("adArchiveID","INTEGER"),
    bigquery.SchemaField("archiveTypes","INTEGER"),
    bigquery.SchemaField("categories","INTEGER"),
    bigquery.SchemaField("collationCount","INTEGER"),
    bigquery.SchemaField("collationID","INTEGER"),
    bigquery.SchemaField("currency","STRING"),
    bigquery.SchemaField("endDate","TIMESTAMP"),
    bigquery.SchemaField("entityType","STRING"),
    bigquery.SchemaField("favInfo","STRING"),
    bigquery.SchemaField("gatedType","STRING"),
    bigquery.SchemaField("hiddenSafetyData","BOOLEAN"),
    bigquery.SchemaField("hideDataStatus","STRING"),
    bigquery.SchemaField("impressionsText","STRING"),
    bigquery.SchemaField("impressionsIndex","STRING"),
    bigquery.SchemaField("isActive","BOOLEAN"),
    bigquery.SchemaField("isProfilePage","BOOLEAN"),
    bigquery.SchemaField("reachEstimate","STRING"),
    bigquery.SchemaField("snapshot_ad_creative_id","INTEGER"),
    bigquery.SchemaField("snapshot_byline","STRING"),
    bigquery.SchemaField("snapshot_caption","STRING"),
    bigquery.SchemaField("snapshot_cta_text","STRING"),
    bigquery.SchemaField("snapshot_effective_auth_category","STRING"),
    bigquery.SchemaField("snapshot_event","STRING"),
    bigquery.SchemaField("snapshot_extra_images","STRING"),
    bigquery.SchemaField("snapshot_extra_links","STRING"),
    bigquery.SchemaField("snapshot_extra_texts","STRING"),
    bigquery.SchemaField("snapshot_extra_videos","STRING"),
    bigquery.SchemaField("snapshot_instagram_shopping_products","STRING"),
    bigquery.SchemaField("snapshot_display_format","STRING"),
    bigquery.SchemaField("snapshot_page_welcome_message","STRING"),
    bigquery.SchemaField("snapshot_creation_time","TIMESTAMP"),
    bigquery.SchemaField("snapshot_page_id","INTEGER"),
    bigquery.SchemaField("snapshot_page_name","STRING"),
    bigquery.SchemaField("spend","STRING"),
    bigquery.SchemaField("startDate","TIMESTAMP"),
    bigquery.SchemaField("stateMediaRunLabel","STRING"),
    bigquery.SchemaField("publisherPlatform","STRING"),
    bigquery.SchemaField("menuItems","STRING"),
    bigquery.SchemaField("ScrapedDate","Date")
]

SNAPSHOT_SCHEMA = [
    bigquery.SchemaField("ad_creative_id","INTEGER"),
    bigquery.SchemaField("body","STRING"),
    bigquery.SchemaField("caption","STRING"),
    bigquery.SchemaField("cta_text","STRING"),
    bigquery.SchemaField("cta_type","STRING"),
    bigquery.SchemaField("title","STRING"),
    bigquery.SchemaField("link_description","STRING"),
    bigquery.SchemaField("link_url","STRING"),
    bigquery.SchemaField("image_url_ori","STRING"),
    bigquery.SchemaField("video_hd_url","STRING"),
    bigquery.SchemaField("adArchiveId","INTEGER"),
    bigquery.SchemaField("ScrapedDate","Date"),
    bigquery.SchemaField("media_type","STRING")
]